import Head from 'next/head'
import Botao from './components/butao-calculadora'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <div className="flex justify-center p-4">
        <Head>
          <title>Teste deploy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className='h-max w-[500px] flex flex-col items-center border-gray-dark border rounded-md shadow-gray-light shadow-xl'>
          <h1 className='text-2xl font-black m-6'>Titulo</h1>
          {/* VISOR */}
          <div className='h-[60px] w-4/5 p-4 m-6 bg-gray-bluered rounded-sm shadow-gray-dark shadow-sm flex items-center justify-end'>
            <h1 className='text-xl font-black text-gray-dark'>1+2</h1>
          </div>
          {/* TECLADO */}

          <div>
            <div className='flex gap-9 max-w-[350px]'>
              <Botao number='C' />
              <Botao number='/' />
              <Botao number='X' />
              <Botao number='-' />
            </div>
            <div className='h-9'></div>
            <div className='flex justify-start'>
              <div className='flex flex-wrap gap-9 max-w-[250px]'>
                <Botao number='7' />
                <Botao number='8' />
                <Botao number='9' />
                <Botao number='4' />
                <Botao number='5' />
                <Botao number='6' />
                <Botao number='1' />
                <Botao number='2' />
                <Botao number='3' />
              </div>
              <div className='flex-col flex gap-9'>
                <Botao number='+'/>
                <Botao number='.'/>
              </div>
            </div>
          </div>
          {/* <div className='flex flex-wrap m-6 justify-center gap-9 max-w-[350px]'>


            <Botao number='7' />
            <Botao number='8' />
            <Botao number='9' />
            <Botao number='+' />
            <Botao number='4' />
            <Botao number='5' />
            <Botao number='6' />
            <Botao number='.' />
            <Botao number='1' />
            <Botao number='2' />
            <Botao number='3' />
            <Botao number='Enter' />
          </div> */}
        </section>
        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
    </>

  )
}
